---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: monocle
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - args:
            - monocle
            - api
          env:
            - name: MONOCLE_CONFIG
              value: /etc/monocle/config.yaml
            - name: MONOCLE_ELASTIC_URL
              value: http://elastic:9200
            - name: MONOCLE_PUBLIC_URL
              value: http://api-monocle.mycluster-dal10-b3-488804-3626522b15eedb880d7b99992e225c1b-0000.us-south.containers.appdomain.cloud
            - name: CHANGE_ME
              valueFrom:
                secretKeyRef:
                  name: crawler-secret
                  key: CHANGE_ME
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: GITHUB_TOKEN
            - name: crawler-token
              valueFrom:
                secretKeyRef:
                  name: crawler-secret
                  key: CRAWLERS_API_KEY

          image: quay.io/change-metrics/monocle:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 6
            timeoutSeconds: 60
          name: api
          ports:
            - containerPort: 8080
              name: http-rest-api
          resources: {}
          volumeMounts:
            - mountPath: /etc/monocle
              name: monocle-config-volume
      restartPolicy: Always
      volumes:
        - name: monocle-config-volume
          configMap:
            defaultMode: 420
            name: monocle-config # ./monocle-config.yaml
status: {}
