---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: crawler
    app.kubernetes.io/component: crawler
    app.kubernetes.io/part-of: monocle
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crawler
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: crawler
        app.kubernetes.io/component: crawler
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - args:
            - monocle
            - crawler
          env:
            - name: MONOCLE_CONFIG
              value: /etc/monocle/config.yaml
            - name: MONOCLE_PUBLIC_URL
              value: http://api:8080
            - name: CONFIG
              value: /etc/monocle/config.yaml
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: GITHUB_TOKEN
            - name: crawler-token
              valueFrom:
                secretKeyRef:
                  name: crawler-secret
                  key: CRAWLERS_API_KEY
            - name: CHANGE_ME
              valueFrom:
                secretKeyRef:
                  name: crawler-secret
                  key: CHANGE_ME
          image: quay.io/change-metrics/monocle:latest
          name: crawler
          resources: {}
          livenessProbe:
            httpGet:
              path: /health
              port: 9001
            failureThreshold: 6
            timeoutSeconds: 60
          volumeMounts:
            - mountPath: /etc/monocle
              name: monocle-config-volume
      restartPolicy: Always
      volumes:
        - name: monocle-config-volume
          configMap:
            defaultMode: 420
            name: monocle-config
status: {}
