---
apiVersion: v1
# created manually using the command: 
# oc create configmap --from-file=config.yaml monocle-config --dry-run=client -oyaml
kind: ConfigMap
metadata:
  name: monocle-config
  labels:
    app.kubernetes.io/part-of: monocle
data:
  config.yaml: |+
    workspaces:
      - name: oadp
        crawlers_api_key: CHANGE_ME
        crawlers:
          - name: openshift
            provider:
              github_organization: openshift
              github_repositories:
                - oadp-operator
                - velero
                - restic
                - openshift-velero-plugin
                - velero-plugin-for-aws
                - velero-plugin-for-gcp
                - velero-plugin-for-microsoft-azure
                - velero-plugin-for-csi
            update_since: '2022-06-01'
          - name: konveyor
            provider:
              github_organization: konveyor
              github_repositories:
                - volume-snapshot-mover
            update_since: '2022-06-01'
          - name: kubevirt
            provider:
              github_organization: kubevirt
              github_repositories:
                - kubevirt-velero-plugin
            update_since: '2022-06-01'
 